# 服务器配置
[server]
host = "127.0.0.1"
port = 8080

# 数据库配置
[database]
url = "postgres://postgres:123456@localhost:5432/student"
max_connections = 5

# JWT配置
[jwt]
secret = "your_secret_key_change_this_in_production"
expiration = 1140                                    # 过期时间（分钟）
